theme: jekyll-theme-minimal
title: Imad Saddik — Software Engineer & AI Enthusiast
description: Imad Saddik's CV, projects, courses, and professional journey in AI, data science, and software engineering.
